### ISSUE TITLE
[Localise][Track2] Evaluate TartanVO

### ISSUE THREAD

**Issue by jonyktan** [DinoHub/devmgmt-monkeybotics#123]

**Comment by jonyktan** [comment]
**TODO**

- [ ] Understand how TartanVO works (TartanAir data collection, TartanVO training, TartanVO evaluation, TartanVO inference)

- [ ] Test TartanVO in virtual replica of our environment

- [ ] Test TartanVO on collected data from real environment

- [ ] Use TartanAir pipeline to collect training data for TartanVO from our virtual environments

- [ ] Check if TartanVO performance improves when data collected from TartanAir is improved/increased

- [ ] Modify TartanVO to use data from multiple frames (more history) to overcome lousy frames

- [ ] Check if TartanVO performance improves when multi-frame is used

- [ ] Check TartanVO performance on possible UAV compute hardware

**Comment by AlexanderWCX** [comment]
Tested and ran TartanVO on my dev setup already, still need to figure out how to use the DF recording as a custom dataset instead of the test dataset provided by TartanVO
